name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          latexmk_use_xelatex: true
