name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install language packages
        run: sudo apt install -y texlive-base texlive-xetex texlive-lang-chinese latexmk
      - name: Download the fonts
        run: for i in simhei.ttf simkai.ttf simsun.ttc simsunb.ttf simfang.ttf; do wget -P fonts/ https://xugr.keybase.pub/static/fonts/$i; done
      - name: Copy the fonts
        run: mkdir -p ~/.local/share/fonts && cp -r fonts/* ~/.local/share/fonts/
      - name: Download latex science
        run: sudo apt-get install texlive-science
      - name: Build font information caches
        run: fc-cache -rv
      - name: Compile LaTeX document
        run: xelatex report.tex
